#!/bin/bash

# Install kubectl
sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update -y
sudo apt-get install -y kubectl

# Install Docker
sudo apt-get update && \
    sudo apt-get install docker.io -y

# Install Minikube
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
sudo apt install conntrack -y

# Installing Jenkins
docker network create jenkins

mkdir ~/jenkins

cat << 'EOF' > ~/jenkins/dockerfile
FROM jenkins/jenkins:latest
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
EOF

docker build -t node-jenkins:dos ~/jenkins/

# Running Jenkins
docker run \
  --name jenkins-node-k8s \
  --rm \
  --detach \
  --network jenkins \
  --env DOCKER_HOST=tcp://docker:2376 \
  --env DOCKER_CERT_PATH=/certs/client \
  --env DOCKER_TLS_VERIFY=1 \
  --publish 9080:8080 \
  --publish 50000:50000 \
  --volume jenkins-data:/var/jenkins_home \
  --volume jenkins-docker-certs:/certs/client:ro \
  node-jenkins:dos

sudo apt install openjdk-11-jre-headless -y

minikube start --vm-driver=none

sudo wget http://localhost:9080/jnlpJars/jenkins-cli.jar

sudo java -jar jenkins-cli.jar -s http://localhost:9080/ install-plugin \
ant:latest \
antisamy-markup-formatter:latest \
build-timeout:latest \
cloudbees-folder:latest \
configuration-as-code:latest \
credentials-binding:latest \
email-ext:latest \
git:latest \
github-branch-source:latest \
gradle:latest \
ldap:latest \
mailer:latest \
matrix-auth:latest \
pam-auth:latest \
pipeline-github-lib:latest \
pipeline-stage-view:latest \
ssh-slaves:latest \
timestamper:latest \
workflow-aggregator:latest \
ws-cleanup:latest -deploy -restart