#!/bin/bash

instanceip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)

# Install Docker
sudo apt-get update && \
    sudo apt-get install docker.io -y

mkdir ~/jenkins

cat  << 'EOF' > ~/jenkins/casc.yaml
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://instanceip:9080/
jobs:
  - script: >
      job('example') {
          steps {
              shell('echo Hello World!')
          }
      }
  - script: >
      job('testJob2') {
          scm {
              git('git://github.com/quidryan/aws-sdk-test.git')
          }
          triggers {
              scm('H/15 * * * *')
          }
          steps {
              maven('-e clean test')
          }
      }
EOF

sed -i 's/instanceip/'$instanceip'/g' ~/jenkins/casc.yaml

cat << 'EOF' > ~/jenkins/plugins.txt
ant:latest
antisamy-markup-formatter:latest
authorize-project:latest
build-timeout:latest
cloudbees-folder:latest
configuration-as-code:latest
credentials-binding:latest
email-ext:latest
git:latest
github-branch-source:latest
gradle:latest
job-dsl:latest
ldap:latest
mailer:latest
matrix-auth:latest
pam-auth:latest
pipeline-github-lib:latest
pipeline-stage-view:latest
ssh-slaves:latest
timestamper:latest
workflow-aggregator:latest
ws-cleanup:latest
EOF

cat << 'EOF' > ~/jenkins/dockerfile
FROM jenkins/jenkins:latest
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc.yaml
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
COPY casc.yaml /var/jenkins_home/casc.yaml
EOF

docker build -t jenkins:dos ~/jenkins/

# Running Jenkins
docker run --name jenkins --rm -p 9080:8080 --env JENKINS_ADMIN_ID=admin --env JENKINS_ADMIN_PASSWORD=piraculous jenkins:dos

curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
sudo apt-get install apt-transport-https --yes
echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update -y
sudo apt-get install helm -y